# Generated by Django 4.2.7 on 2026-01-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_text', models.TextField()),
                ('jd_text', models.TextField()),
                ('skill_match', models.FloatField()),
                ('experience_match', models.FloatField()),
                ('education_match', models.FloatField()),
                ('semantic_similarity', models.FloatField()),
                ('overall_match', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
